package scenarios

// StressIDStringToID includes all defined workload IDs.
var StressIDStringToID = map[string]StressID{
	"CONCURRENT_PUTS":            ConcurrentPuts,
	"BURST_WRITES":               BurstWrites,
	"SUSTAINED_LOAD":             SustainedLoad,
	"RAMP_UP_LOAD":               RampUpLoad,
	"MIXED_WORKLOAD":             MixedWorkload,
	"LARGE_VALUES":               LargeValues,
	"MANY_KEYS":                  ManyKeys,
	"HIGH_CONTENTION":            HighContention,
	"SEQUENTIAL_WRITES":          SequentialWrites,
	"RANDOM_READS":               RandomReads,
	"WATCH_PROGRESS_NOTIFY":      WatchProgressNotify,
	"LEASE_INTENSIVE_WORKLOAD":   LeaseIntensiveWorkload,
	"LIST_PAGINATION_HEAVY":      ListPaginationHeavy,
	"OPTIMISTIC_CONCURRENCY_TXN": OptimisticConcurrencyTxn,
	"WATCH_MANY_PREFIXES":        WatchManyPrefixes,
	"COMPACT_DURING_LOAD":        CompactDuringLoad,
	"WATCH_WITH_CHURN":           WatchWithChurn,
	"NAMESPACE_ISOLATION_HEAVY":  NamespaceIsolationHeavy,
	"TXN_MULTI_KEY_UPDATE":       TxnMultiKeyUpdate,
	"LEADER_ELECTION_CONTENTION": LeaderElectionContention,
	"WATCH_BOOKMARK_HEAVY":       WatchBookmarkHeavy,
	"K8S_POD_LIFECYCLE_CHURN":    K8sPodLifecycleChurn,
	"K8S_NODE_HEARTBEAT_LEASES":  K8sNodeHeartbeatLeases,
	"K8S_MIXED_APISERVER":        K8sMixedApiserver,
	"K8S_CRD_HEAVY_CHURN":        K8sCRDHeavyChurn,
}

// StressIDStringToRunnerFunc maps workload IDs to runner functions.
var StressIDStringToRunnerFunc = map[string]func(r StressRunner){
	"CONCURRENT_PUTS":            RunConcurrentPuts,
	"BURST_WRITES":               RunBurstWrites,
	"SUSTAINED_LOAD":             RunSustainedLoad,
	"RAMP_UP_LOAD":               RunRampUpLoad,
	"MIXED_WORKLOAD":             RunMixedWorkload,
	"LARGE_VALUES":               RunLargeValues,
	"MANY_KEYS":                  RunManyKeys,
	"HIGH_CONTENTION":            RunHighContention,
	"SEQUENTIAL_WRITES":          RunSequentialWrites,
	"RANDOM_READS":               RunRandomReads,
	"WATCH_PROGRESS_NOTIFY":      RunWatchProgressNotify,
	"LEASE_INTENSIVE_WORKLOAD":   RunLeaseIntensiveWorkload,
	"LIST_PAGINATION_HEAVY":      RunListPaginationHeavy,
	"OPTIMISTIC_CONCURRENCY_TXN": RunOptimisticConcurrencyTxn,
	"WATCH_MANY_PREFIXES":        RunWatchManyPrefixes,
	"COMPACT_DURING_LOAD":        RunCompactDuringLoad,
	"WATCH_WITH_CHURN":           RunWatchWithChurn,
	"NAMESPACE_ISOLATION_HEAVY":  RunNamespaceIsolationHeavy,
	"TXN_MULTI_KEY_UPDATE":       RunTxnMultiKeyUpdate,
	"LEADER_ELECTION_CONTENTION": RunLeaderElectionContention,
	"WATCH_BOOKMARK_HEAVY":       RunWatchBookmarkHeavy,
	"K8S_POD_LIFECYCLE_CHURN":    RunK8sPodLifecycleChurn,
	"K8S_NODE_HEARTBEAT_LEASES":  RunK8sNodeHeartbeatLeases,
	"K8S_MIXED_APISERVER":        RunK8sMixedApiserver,
	"K8S_CRD_HEAVY_CHURN":        RunK8sCRDHeavyChurn,
}

// StressIDToRunner maps StressID to the concrete runner.
var StressIDToRunner = map[StressID]func(r StressRunner){
	ConcurrentPuts:           RunConcurrentPuts,
	BurstWrites:              RunBurstWrites,
	SustainedLoad:            RunSustainedLoad,
	RampUpLoad:               RunRampUpLoad,
	MixedWorkload:            RunMixedWorkload,
	LargeValues:              RunLargeValues,
	ManyKeys:                 RunManyKeys,
	HighContention:           RunHighContention,
	SequentialWrites:         RunSequentialWrites,
	RandomReads:              RunRandomReads,
	WatchProgressNotify:      RunWatchProgressNotify,
	LeaseIntensiveWorkload:   RunLeaseIntensiveWorkload,
	ListPaginationHeavy:      RunListPaginationHeavy,
	OptimisticConcurrencyTxn: RunOptimisticConcurrencyTxn,
	WatchManyPrefixes:        RunWatchManyPrefixes,
	CompactDuringLoad:        RunCompactDuringLoad,
	WatchWithChurn:           RunWatchWithChurn,
	NamespaceIsolationHeavy:  RunNamespaceIsolationHeavy,
	TxnMultiKeyUpdate:        RunTxnMultiKeyUpdate,
	LeaderElectionContention: RunLeaderElectionContention,
	WatchBookmarkHeavy:       RunWatchBookmarkHeavy,
}
