package scenarios

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PutEmptyKeyShouldError-0]
	_ = x[PutLargeShouldError-1]
	_ = x[PutAndGetWithLatestRevision-2]
	_ = x[PutAndGetWithOldRevision-3]
	_ = x[PutAndGetWithPrefix-4]
	_ = x[PutAndGetWithFromKey-5]
	_ = x[PutAndGetWithNamespace-6]
	_ = x[PutAndGetWithSort-7]
	_ = x[PutAndGetWithOp-8]
	_ = x[PutAndDelete-9]
	_ = x[PutAndDeleteWithPrefix-10]
	_ = x[PutAndDeleteAndGetWithOldRevision-11]
	_ = x[PutLinearizability-12]
	_ = x[PutWithLeaseTimeToLive-13]
	_ = x[PutWithLeaseNotFound-14]
	_ = x[PutWithLeaseAndRevoke-15]
	_ = x[PutWithLeaseKeepalive-16]
	_ = x[PutWithLeaseKeepaliveOneSecond-17]
	_ = x[PutWithLeaseKeepaliveOnce-18]
	_ = x[PutWithLeaseKeepaliveFullResponseQueue-19]
	_ = x[PutWithIgnoreValue-20]
	_ = x[PutWithIgnoreLease-21]
	_ = x[LeaseTooLarge-22]
	_ = x[LeaseKeepaliveRevoke-23]
	_ = x[GetEmptyKey-24]
	_ = x[GetWithPrefix-25]
	_ = x[GetWithFromKey-26]
	_ = x[GetWithRange-27]
	_ = x[GetWithLimitAndCount-28]
	_ = x[GetWithRevisionFilters-29]
	_ = x[GetWithRequireLeader-30]
	_ = x[DeleteEmptyKey-31]
	_ = x[DeleteAllWithPrefix-32]
	_ = x[DeleteAllWithFromKey-33]
	_ = x[DeleteWithRange-34]
	_ = x[DeleteWithPrecondition-35]
	_ = x[Compact-36]
	_ = x[TxnPutOne-37]
	_ = x[TxnPutMultiple-38]
	_ = x[TxnKeyExists-39]
	_ = x[TxnKeyMissing-40]
	_ = x[TxnCompareRange-41]
	_ = x[TxnCompareModrevision-42]
	_ = x[TxnNested-43]
	_ = x[TxnErrorDuplicateKey-44]
	_ = x[TxnErrorTooManyOps-45]
	_ = x[WatchEmptyKey-46]
	_ = x[WatchAndPut-47]
	_ = x[WatchWithPrevKv-48]
	_ = x[WatchAndPutWithOldRevision-49]
	_ = x[WatchAndPutWithIgnoreValue-50]
	_ = x[WatchAndPutWithNamespace-51]
	_ = x[WatchWithCompactedRevision-52]
	_ = x[WatchEventType-53]
	_ = x[WatchWithPrefix-54]
	_ = x[WatchWithRange-55]
	_ = x[WatchWithMultipleWatchers-56]
	_ = x[WatchCancelInflight-57]
	_ = x[WatchCancelImmediate-58]
	_ = x[WatchCancelInit-59]
	_ = x[WatchCancelOverlappingContext-60]
	_ = x[WatchCancelClose-61]
	_ = x[WatchWithFilter-62]
	_ = x[WatchWithCreatedNotification-63]
	_ = x[WatchWithProgressNotify-64]
	_ = x[WatchWithRequestProgress-65]
	_ = x[WatchWithTooLargeResponse-66]
	_ = x[WatchWithFragmentedLargeResponse-67]
	_ = x[MirrorSyncBase-68]
	_ = x[MirrorSyncUpdates-69]
	_ = x[ConcurrencyMutexLock-70]
	_ = x[ConcurrencyMutexTrylock-71]
	_ = x[ConcurrencyMutexLockWithRevokedSession-72]
	_ = x[ConcurrencyMutexLockWithSessionRevoke-73]
	_ = x[ConcurrencyElectionCampaign-74]
	_ = x[ConcurrencyElectionResume-75]
	_ = x[ConcurrencyStmApply-76]
	_ = x[LeasingPutAndGet-77]
	_ = x[LeasingPutAndGetWithPrefix-78]
	_ = x[LeasingPutAndGetInvalidateNew-79]
	_ = x[LeasingPutAndGetInvalidateExisting-80]
	_ = x[LeasingPutAndGetWithPrevKv-81]
	_ = x[LeasingPutAndGetWithRev-82]
	_ = x[LeasingPutAndGetWithOpts-83]
	_ = x[LeasingPutConcurrent-84]
	_ = x[LeasingPutAndGetOverwriteResponse-85]
	_ = x[LeasingPutAndDeleteWithPrefix-86]
	_ = x[LeasingPutAndDeleteWithFromKey-87]
	_ = x[LeasingPutAndDeleteRangeWithContendingTxn-88]
	_ = x[LeasingPutAndDeleteRangeWithContendingDelete-89]
	_ = x[LeasingPutAndGetAndDeleteConcurrent-90]
	_ = x[LeasingDeleteOwner-91]
	_ = x[LeasingDeleteNonOwner-92]
	_ = x[LeasingTxnOwnerGet-93]
	_ = x[LeasingTxnOwnerGetWithPrefix-94]
	_ = x[LeasingTxnOwnerDelete-95]
	_ = x[LeasingTxnOwnerDeleteWithPrefix-96]
	_ = x[LeasingTxnNonOwnerPut-97]
	_ = x[LeasingTxnRandIfThenOrElse-98]
	_ = x[LeasingTxnAtomicCache-99]
	_ = x[LeasingTxnRangeCmp-100]
	_ = x[LeasingDo-101]
	_ = x[LeasingLeaseReuseWindow-102]
	_ = x[MaintenanceStatus-103]
	_ = x[MaintenanceSnapshot-104]
	_ = x[ClusterMemberList-105]
	_ = x[LeaseExpirationAutoDelete-106]
	_ = x[WatchResumeAfterDisconnect-107]
	_ = x[GetWithContinueToken-108]
	_ = x[TLSClientAuth-109]
	_ = x[ResourceSizeEstimation-110]
	_ = x[ErrorCompacted-111]
	_ = x[ErrorFutureRev-112]
	_ = x[TxnCompareCreaterevision-113]
	_ = x[TxnCompareVersion-114]
	_ = x[TxnCompareValue-115]
	_ = x[DeleteWithPrevKv-116]
	_ = x[WatchBookmarkDelivery-117]
	_ = x[HeaderRevisionMonotonic-118]
	_ = x[ModRevisionConsistency-119]
	_ = x[PutWithPrevKv-120]
	_ = x[LeaseList-121]
	_ = x[TxnCompareLease-122]
	_ = x[GetWithKeysOnly-123]
	_ = x[PutWithLeaseAttach-124]
	_ = x[WatchInitialEvents-125]
	_ = x[TxnMultiOpAtomicity-126]
	_ = x[CompactRevisionRetention-127]
	_ = x[WatchOrderingGuarantee-128]
	_ = x[LeaseGrantTTLBounds-129]
	_ = x[MaintenanceDefragment-130]
	_ = x[MaintenanceHashKv-131]
}

const _IDName = "PUT_EMPTY_KEY_SHOULD_ERRORPUT_LARGE_SHOULD_ERRORPUT_AND_GET_WITH_LATEST_REVISIONPUT_AND_GET_WITH_OLD_REVISIONPUT_AND_GET_WITH_PREFIXPUT_AND_GET_WITH_FROM_KEYPUT_AND_GET_WITH_NAMESPACEPUT_AND_GET_WITH_SORTPUT_AND_GET_WITH_OPPUT_AND_DELETEPUT_AND_DELETE_WITH_PREFIXPUT_AND_DELETE_AND_GET_WITH_OLD_REVISIONPUT_LINEARIZABILITYPUT_WITH_LEASE_TIME_TO_LIVEPUT_WITH_LEASE_NOT_FOUNDPUT_WITH_LEASE_AND_REVOKEPUT_WITH_LEASE_KEEPALIVEPUT_WITH_LEASE_KEEPALIVE_ONE_SECONDPUT_WITH_LEASE_KEEPALIVE_ONCEPUT_WITH_LEASE_KEEPALIVE_FULL_RESPONSE_QUEUEPUT_WITH_IGNORE_VALUEPUT_WITH_IGNORE_LEASELEASE_TOO_LARGELEASE_KEEPALIVE_REVOKEGET_EMPTY_KEYGET_WITH_PREFIXGET_WITH_FROM_KEYGET_WITH_RANGEGET_WITH_LIMIT_AND_COUNTGET_WITH_REVISION_FILTERSGET_WITH_REQUIRE_LEADERDELETE_EMPTY_KEYDELETE_ALL_WITH_PREFIXDELETE_ALL_WITH_FROM_KEYDELETE_WITH_RANGEDELETE_WITH_PRECONDITIONCOMPACTTXN_PUT_ONETXN_PUT_MULTIPLETXN_KEY_EXISTSTXN_KEY_MISSINGTXN_COMPARE_RANGETXN_COMPARE_MODREVISIONTXN_NESTEDTXN_ERROR_DUPLICATE_KEYTXN_ERROR_TOO_MANY_OPSWATCH_EMPTY_KEYWATCH_AND_PUTWATCH_WITH_PREV_KVWATCH_AND_PUT_WITH_OLD_REVISIONWATCH_AND_PUT_WITH_IGNORE_VALUEWATCH_AND_PUT_WITH_NAMESPACEWATCH_WITH_COMPACTED_REVISIONWATCH_EVENT_TYPEWATCH_WITH_PREFIXWATCH_WITH_RANGEWATCH_WITH_MULTIPLE_WATCHERSWATCH_CANCEL_INFLIGHTWATCH_CANCEL_IMMEDIATEWATCH_CANCEL_INITWATCH_CANCEL_OVERLAPPING_CONTEXTWATCH_CANCEL_CLOSEWATCH_WITH_FILTERWATCH_WITH_CREATED_NOTIFICATIONWATCH_WITH_PROGRESS_NOTIFYWATCH_WITH_REQUEST_PROGRESSWATCH_WITH_TOO_LARGE_RESPONSEWATCH_WITH_FRAGMENTED_LARGE_RESPONSEMIRROR_SYNC_BASEMIRROR_SYNC_UPDATESCONCURRENCY_MUTEX_LOCKCONCURRENCY_MUTEX_TRYLOCKCONCURRENCY_MUTEX_LOCK_WITH_REVOKED_SESSIONCONCURRENCY_MUTEX_LOCK_WITH_SESSION_REVOKECONCURRENCY_ELECTION_CAMPAIGNCONCURRENCY_ELECTION_RESUMECONCURRENCY_STM_APPLYLEASING_PUT_AND_GETLEASING_PUT_AND_GET_WITH_PREFIXLEASING_PUT_AND_GET_INVALIDATE_NEWLEASING_PUT_AND_GET_INVALIDATE_EXISTINGLEASING_PUT_AND_GET_WITH_PREV_KVLEASING_PUT_AND_GET_WITH_REVLEASING_PUT_AND_GET_WITH_OPTSLEASING_PUT_CONCURRENTLEASING_PUT_AND_GET_OVERWRITE_RESPONSELEASING_PUT_AND_DELETE_WITH_PREFIXLEASING_PUT_AND_DELETE_WITH_FROM_KEYLEASING_PUT_AND_DELETE_RANGE_WITH_CONTENDING_TXNLEASING_PUT_AND_DELETE_RANGE_WITH_CONTENDING_DELETELEASING_PUT_AND_GET_AND_DELETE_CONCURRENTLEASING_DELETE_OWNERLEASING_DELETE_NON_OWNERLEASING_TXN_OWNER_GETLEASING_TXN_OWNER_GET_WITH_PREFIXLEASING_TXN_OWNER_DELETELEASING_TXN_OWNER_DELETE_WITH_PREFIXLEASING_TXN_NON_OWNER_PUTLEASING_TXN_RAND_IF_THEN_OR_ELSELEASING_TXN_ATOMIC_CACHELEASING_TXN_RANGE_CMPLEASING_DOLEASING_LEASE_REUSE_WINDOWMAINTENANCE_STATUSMAINTENANCE_SNAPSHOTCLUSTER_MEMBER_LISTLEASE_EXPIRATION_AUTO_DELETEWATCH_RESUME_AFTER_DISCONNECTGET_WITH_CONTINUE_TOKENTLS_CLIENT_AUTHRESOURCE_SIZE_ESTIMATIONERROR_COMPACTEDERROR_FUTURE_REVTXN_COMPARE_CREATEREVISIONTXN_COMPARE_VERSIONTXN_COMPARE_VALUEDELETE_WITH_PREV_KVWATCH_BOOKMARK_DELIVERYHEADER_REVISION_MONOTONICMOD_REVISION_CONSISTENCYPUT_WITH_PREV_KVLEASE_LISTTXN_COMPARE_LEASEGET_WITH_KEYS_ONLYPUT_WITH_LEASE_ATTACHWATCH_INITIAL_EVENTSTXN_MULTI_OP_ATOMICITYCOMPACT_REVISION_RETENTIONWATCH_ORDERING_GUARANTEELEASE_GRANT_TTL_BOUNDSMAINTENANCE_DEFRAGMENTMAINTENANCE_HASH_KV"

var _IDIndex = [...]uint16{0, 26, 48, 80, 109, 132, 157, 183, 204, 223, 237, 263, 303, 322, 349, 373, 398, 422, 457, 486, 530, 551, 572, 587, 609, 622, 637, 654, 668, 692, 717, 740, 756, 778, 802, 819, 843, 850, 861, 877, 891, 906, 923, 946, 956, 979, 1001, 1016, 1029, 1047, 1078, 1109, 1137, 1166, 1182, 1199, 1215, 1243, 1264, 1286, 1303, 1335, 1353, 1370, 1401, 1427, 1454, 1483, 1519, 1535, 1554, 1576, 1601, 1644, 1686, 1715, 1742, 1763, 1782, 1813, 1847, 1886, 1918, 1946, 1975, 1997, 2035, 2069, 2105, 2153, 2204, 2245, 2265, 2289, 2310, 2343, 2367, 2403, 2428, 2460, 2484, 2505, 2515, 2541, 2559, 2579, 2598, 2626, 2655, 2678, 2693, 2717, 2732, 2748, 2774, 2793, 2810, 2829, 2852, 2877, 2901, 2917, 2927, 2944, 2962, 2983, 3003, 3025, 3051, 3075, 3097, 3119, 3138}

func (i ID) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_IDIndex)-1 {
		return "ID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IDName[_IDIndex[idx]:_IDIndex[idx+1]]
}
